// Source: http://www.avrfreaks.net/comment/1978691#comment-1978691


// TODO: Make this compile and see if I can get it working with just UART-SPI

/*----------------------------------------------------------------------*/
/* FAT file system sample project for FatFs            (C)ChaN, 2014    */
/*----------------------------------------------------------------------*/


#include <avr/io.h>
#include <avr/interrupt.h>
//#include <string.h>
//#include "xitoa.h"
#include "ff.h"
#include "diskio.h"

//FUSES = {0xF7, 0x91, 0xFC};		/* ATmega1284p fuses: Low, High, Extended.
//This is the fuse settings for this project. The fuse bits will be included
//in the output hex file with program code. However some old flash programmers
//cannot load the fuse bits from hex file. If it is the case, remove this line
//and use these values to program the fuse bits. */


//BYTE Buff[4096];	/* Working buffer */

FATFS FatFs;		/* File system object for each logical drive */
FIL File;		/* File object */

volatile UINT Timer;	/* Performance timer (100Hz increment) */

///*---------------------------------------------------------*/
///* 100Hz timer interrupt generated by OC0A                 */
///*---------------------------------------------------------*/
ISR(TIMER2_COMP_vect)
{
    Timer++;            /* Performance counter for this module */
    disk_timerproc();   /* Drive timer procedure of low level disk I/O module */
}


static
void ioinit (void)
{
	MCUCR = _BV(JTD); MCUCR = _BV(JTD);	/* Disable JTAG */

    /* Start 100Hz system timer (TC2.OC) */
    OCR2 = F_CPU / 1024 / 100 - 1;
    TCCR2 = 0b00001101;
    TIMSK |= _BV(OCIE2);

	sei();
}

void myprintf(char * line) {
    // on a good day we might print something here!
}

/*-----------------------------------------------------------------------*/
/* Main                                                                  */
int main (void)
{
	char line[120];
	DSTATUS ds;
	FRESULT fr;

	ioinit();				/* Initialize port settings and start system timer process */

	// not really necessary to call this necessary but this will be
	// the first sign that something is alive
	ds = disk_initialize(0);
	f_mount(&FatFs, "", 0);
	fr = f_open(&File, "test.fil", FA_READ);
	if (fr == FR_OK) {
		/* Read all lines and display it */
		while (f_gets(line, sizeof line, &File))
			myprintf(line);

		/* Close the file */
		f_close(&File);
	}

	while(1);
}

